version: '3.1'
services:
  app:
    build: .
    platform: 'linux/x86_64'
    command: ["./app"]
    ports:
      - "8080:8080"
    volumes:
        - .:/go/src/app
    environment:
        - GOOS=linux
        - GOARCH=amd64
        - CGO_ENABLED=0
